runtime: nodejs12
env: standard

env_variables:
  # GOOGLE
  GOOGLE_CLIENT_ID: '87183063500-d60btrcnk7jdn9j3impgqte7bt35d88i.apps.googleusercontent.com'
  GOOGLE_SECRET: 'S8s_AtnBPXvWXAXK5ZgVHZ97'
  GOOGLE_CALLBACK_URL: 'https://code-snippet-memo.an.r.appspot.com/api/auth/google/callback'
  # DATABASE
  DATABASE_HOST: '/cloudsql/code-snippet-memo:asia-northeast1:code-snippet-memo'
  DATABASE_PORT: 5432
  DATABASE_USERNAME: 'postgres'
  DATABASE_PASSWORD: 'Ev22mrtuggxdoIuheiwj'
  DATABASE_NAME: 'postgres'
  # DATABASE_NAME: 'codesnippetmemo'
  # SESSION
  SESSION_SECRET: 'JSF_sdf88dfb23n_09fdsfsdHJH'

handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
