runtime: nodejs12
env: standard

env_variables:
  # GOOGLE
  GOOGLE_CLIENT_ID: '87183063500-r0p56n9b3k5pg3i6gkh7g06lk7a9eu3a.apps.googleusercontent.com'
  GOOGLE_SECRET: 'suBkxmjiQtg5zY_fHMXxxuSZ'
  # DATABASE
  DATABASE_HOST: '/cloudsql/code-snippet-memo:asia-northeast1:code-snippet-memo'
  DATABASE_PORT: 5432
  DATABASE_USERNAME: 'postgres'
  DATABASE_PASSWORD: 'postgres'
  # DATABASE_PASSWORD: 'LmkxceTbbpjhtzkn30zm'
  DATABASE_NAME: 'postgres'
  # DATABASE_NAME: 'codesnippetmemo'
  # SESSION
  SESSION_SECRET: 'JSF_sdf88dfb23n_09fdsfsdHJH'

handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
